spring.application.name=lingoAlpha1_0
spring.datasource.url=jdbc:mysql://localhost:3306/language_exchange
spring.datasource.username=root
spring.datasource.password=x24528929

#This is to NOT initialize the schema and data files in resource folder, change to always if you want to reinitialize the database
spring.sql.init.mode=never

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080