spring.application.name=lingoAlpha2_0
spring.datasource.url=jdbc:mysql://localhost:3306/lingo
spring.datasource.username=root
spring.datasource.password=x24528929

#This is to NOT initialize the schema and data files in resource folder, change to always if you want to reinitialize the database
#spring.sql.init.mode=never

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT configuration
jwt.secret=d5fe0f5e2a593f7a27326e5d641b788b
jwt.expiration=3600000
